### ISSUE TITLE
Introduce new option --files

### ISSUE THREAD

**Issue by tejaswini-imply** [ccaominh/intellij-inspect#19]
When a PR is raised, existing Intellij inspections run on all files in the given directory option(generally path or project). Do we need to run IntelliJ inspections on the files that the PR has not updated? If not, we can introduce a new option in the project profile (`--files`); if this option is empty, run the IntelliJ-inspections for all files in the directory else, only for the files mentioned.

**Comment by ccaominh** [comment]
The IntelliJ CLI currently only supports analyzing the entire project or a subdirectory:
https://www.jetbrains.com/help/idea/command-line-code-inspector.html#options

To just run inspections on a specific list of files, one possibility is to dynamically generate an inspection scope file that just matches the desired files and then use the `--scope` argument.
